name: label_lens
description: A Flutter app to scan product labels and check ingredient safety for babies.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  
  # Google Sign In
  google_sign_in: ^7.2.0
  
  # State Management
  provider: ^6.1.1
  
  # Image Processing
  image_picker: ^1.0.4
  google_ml_kit: ^0.20.0
  
  # UI
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/ingredients.json