// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiGBAwZNrmT_fhGYqavf2ugyZNXo-Ct-U',
    appId: '1:906201492340:web:0e331a6f182aa267025a21',
    messagingSenderId: '906201492340',
    projectId: 'labellens-1582b',
    authDomain: 'labellens-1582b.firebaseapp.com',
    storageBucket: 'labellens-1582b.firebasestorage.app',
    measurementId: 'G-CDBW00RH26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ayKIo2ndBPyIw8lmhhtZobT5kuujz4U',
    appId: '1:906201492340:android:bd048b2d91dee408025a21',
    messagingSenderId: '906201492340',
    projectId: 'labellens-1582b',
    storageBucket: 'labellens-1582b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxVaXSFoT5C6XmvpTXJjLmKZVdMBy-ZAQ',
    appId: '1:906201492340:ios:dda5088487de695b025a21',
    messagingSenderId: '906201492340',
    projectId: 'labellens-1582b',
    storageBucket: 'labellens-1582b.firebasestorage.app',
    iosClientId: '906201492340-pafc6talo9ce80mi141eq7t604abjett.apps.googleusercontent.com',
    iosBundleId: 'com.example.labelLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxVaXSFoT5C6XmvpTXJjLmKZVdMBy-ZAQ',
    appId: '1:906201492340:ios:dda5088487de695b025a21',
    messagingSenderId: '906201492340',
    projectId: 'labellens-1582b',
    storageBucket: 'labellens-1582b.firebasestorage.app',
    iosClientId: '906201492340-pafc6talo9ce80mi141eq7t604abjett.apps.googleusercontent.com',
    iosBundleId: 'com.example.labelLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiGBAwZNrmT_fhGYqavf2ugyZNXo-Ct-U',
    appId: '1:906201492340:web:0db4da8cc1b4405a025a21',
    messagingSenderId: '906201492340',
    projectId: 'labellens-1582b',
    authDomain: 'labellens-1582b.firebaseapp.com',
    storageBucket: 'labellens-1582b.firebasestorage.app',
    measurementId: 'G-QBSGZKQLRG',
  );
}
